// Markdown for Agents (RFC-style content negotiation) for Cloudflare Pages.
//
// When a request asks for `Accept: text/markdown`, serve the pre-built markdown
// twin of the page (output/<route>/index.md, generated by tools/gen_markdown.py)
// with Content-Type: text/markdown. HTML stays the default for everyone else.
//
// Functions mode (not _worker.js advanced mode), so _headers/_redirects still apply.
// next(new Request(mdUrl)) fetches the static .md asset without re-entering middleware.

export async function onRequest(context) {
  const { request, next } = context;

  const accept = request.headers.get("Accept") || "";
  // Only when markdown is explicitly requested (avoid hijacking browsers).
  if (!/\btext\/markdown\b/i.test(accept)) {
    return next();
  }

  const url = new URL(request.url);
  let path = url.pathname;

  // Map a clean page route to its markdown twin. Skip requests for real files.
  if (path.endsWith("/")) {
    path += "index.md";
  } else if (!path.split("/").pop().includes(".")) {
    path += "/index.md";
  } else {
    return next();
  }

  // Fetch the static .md asset (plain sub-request → no markdown re-negotiation loop).
  const md = await next(new Request(new URL(path, url.origin), { method: "GET" }));
  if (md.status !== 200) {
    return next(); // no markdown twin for this route → serve HTML
  }

  const body = await md.text();
  const headers = new Headers({
    "Content-Type": "text/markdown; charset=utf-8",
    "Vary": "Accept",
    "Cache-Control": "public, max-age=0, must-revalidate",
    // rough token estimate (~4 chars/token) for agents that use it
    "x-markdown-tokens": String(Math.ceil(body.length / 4)),
  });
  return new Response(body, { status: 200, headers });
}
